from typing import List, Protocol
from components.models.llm_model import GenerateOutput, SummarizeOutput, ExpandQueryOutput, AnswerOutput

class LLMInterface(Protocol):
    """LLM contract for DI."""
    def generate(self, prompt: str) -> GenerateOutput: ...
    def summarize(self, text: str, max_tokens: int = 256) -> SummarizeOutput: ...
    def expand_query(self, query: str, max_suggestions: int = 3) -> ExpandQueryOutput: ...
    def answer(self, question: str, context: str) -> AnswerOutput: ...
