from typing import List, Protocol

class LLMInterface(Protocol):
    """LLM contract for DI."""
    def generate(self, prompt: str) -> str: ...
    def summarize(self, text: str, max_tokens: int = 256) -> str: ...
    def expand_query(self, query: str, max_suggestions: int = 3) -> List[str]: ...
    def answer(self, question: str, context: str) -> str: ...
